### ISSUE TITLE
the images in recipes won't open

### ISSUE THREAD

**Issue by ruzkas** [connor-baer/summer#12]
Hi, 
I really like your theme. It has all the necessary tools for a food blogger! I was having a problem seeing the images on individual recipe pages. For instance the Austrian Vanilla Crescents page contains many image files none of which open. Is there anything I can do on my end to fix this? Tx.

**Comment by connor-baer** [comment]
Hey @ruzkas, the image URLs were relative, however, on GitHub Pages there's an additional path segment. So instead of this:

`/assets/images/posts/vanilla-crescents-2-large.jpeg`

...it needed to be this:

`/summer/assets/images/posts/vanilla-crescents-2-large.jpeg`

You can fix this by prefixing the image URLs with the base URL, this will make them into absolute links so that you can avoid the issue altogether. I've applied the fix in this commit: https://github.com/connor-baer/summer/commit/f5a82c3b2aa8a611a752b4ea4640467b8346ef58.

**Comment by ruzkas** [comment]
I worked. Thank you very much!
